FROM node:14-alpine

RUN apk add --no-cache nss 
RUN apk add --no-cache freetype 
RUN apk add --no-cache harfbuzz 
RUN apk add --no-cache ca-certificates 
RUN apk add --no-cache ttf-freefont 
RUN apk add --no-cache chromium 
